site_name: Tres programadores para chile

nav:
- Home: 'index.md'
- Pseudocodigo: 
  - Documentación: pseudocodigo/index.md
  - Ejercicios Resueltos: pseudocodigo/ejerciciosResueltos.md
  - Ejercicios Propuestos: pseudocodigo/ejerciciosPropuestos.md